name: generate-images

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

concurrency:
  group: "generate-images"
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  id-token: write
  actions: write

jobs:
  pre-generate-images:
    # if: contains(github.event.pull_request.labels.*.name, 'skip ci') == false
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_changes.outputs.changed }}
      markdown: ${{ steps.check_changes.outputs.markdown }}
      files: ${{ steps.check_changes.outputs.files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in src/
        id: check_changes
        run: |
          if github.event_name == 'workflow_dispatch'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          MODIFIED_FILES="$(git diff --name-only origin/main...HEAD)<<EOF"
          echo "files=$MODIFIED_FILES" >> $GITHUB_OUTPUT

          if $MODIFIED_FILES | grep -qE '^src/.*/index\.md$'; then
            echo "markdown=true" >> $GITHUB_OUTPUT
          fi
          if $MODIFIED_FILES | grep -qE '^src/.*/index\.(md|jsx|meta\.js)$'; then
            echo "Changes detected in src/, continuing workflow."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in src/, stopping workflow."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  generate-images:
    needs: pre-generate-images
    if: needs.pre-generate-images.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.REPO_TOKEN }}

      - name: Check files
        run: echo ${{ needs.pre-generate-images.outputs.files }}

      - name: Render images for every Mermaid diagram in all Markdown files (*.md) in the repo
        if: needs.pre-generate-images.outputs.changed == 'markdown'
        uses: nielsvaneck/render-md-mermaid@v3

      - name: Generate RWD / OG / Twitter image
        run: |
          npm install
          npm run gen:data

      - name: Check for changes
        id: git_diff
        run: |
          git add src/pages/*
          git status --porcelain | grep -E '^(A|M|\?\?)\s.*\.(jpg|jpeg|png|gif|svg|webp)$' && echo "changed=1" >> $GITHUB_OUTPUT || echo "changed=0"

      - name: Commit if images generated
        if: ${{ steps.git_diff.outputs.changed == 1 }}
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "chore: automatically generate images"
          git push
          gh pr comment ${{ env.PR_NUMBER }} --body "ðŸ¤– Generate images, commit: $(git rev-parse --short HEAD)."
